# THIS FILE IS PART OF Planter PROJECT
# Planter.py - The core part of the Planter library
#
# THIS PROGRAM IS FREE SOFTWARE TOOL, WHICH MAPS MACHINE LEARNING ALGORITHMS TO DATA PLANE, IS LICENSED UNDER Apache-2.0
# YOU SHOULD HAVE RECEIVED A COPY OF WTFPL LICENSE, IF NOT, PLEASE CONTACT THE FOLLOWING E-MAIL ADDRESSES
#
# Copyright (c) 2020-2021 Changgang Zheng
# Copyright (c) Computing Infrastructure Group, Department of Engineering Science, University of Oxford
# E-mail: changgang.zheng@eng.ox.ac.uk or changgangzheng@qq.com
#
# Functions: This file is a license generator.
#            Please refer to ./Docs/Planter_User_Document.pdf or further information.

def add_license(fname, xsa_architecture=False):
    with open(fname, 'w') as headers:
        if xsa_architecture:
            headers.write("/*\n")
        headers.write("########################################################################\n" \
                      "# THIS FILE IS PART OF Planter PROJECT\n" \
                      "# Copyright (c) Changgang Zheng and Computing Infrastructure Group\n" \
                      "# Department of Engineering Science, University of Oxford\n"\
                      "# All rights reserved.\n" \
                      "# E-mail: changgang.zheng@eng.ox.ac.uk or changgangzheng@qq.com\n" \
                      "# Licensed under the Apache License, Version 2.0 (the \"License\");\n" \
                      "# you may not use this file except in compliance with the License.\n" \
                      "# You may obtain a copy of the License at :\n" \
                      "#\n" \
                      "# http://www.apache.org/licenses/LICENSE-2.0\n" \
                      "#\n" \
                      "# Unless required by applicable law or agreed to in writing, software\n" \
                      "# distributed under the License is distributed on an \"AS IS\" BASIS,\n" \
                      "# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n" \
                      "# See the License for the specific language governing permissions and\n" \
                      "# limitations under the License.\n" \
                      "#########################################################################\n" \
                      "# This file was autogenerated\n\n"
                      )
        if xsa_architecture:
             headers.write("*/\n")
