services:
  sn-fw-pkg:
    image: sn-fw-pkg:${OS_CODENAME?}
    build:
      context: pkg-build
      args:
        OS_CODENAME: ${OS_CODENAME?}
    tmpfs:
      # Note: Meson requires that it can execute code from its build dir for a sanity check
      - /build:exec
    volumes:
      - ${PWD}:/source:ro
      - ${PWD}/sn-hw:/sn-hw:ro
      - ${PWD}/sn-stack:/output
    network_mode: host
    environment:
      DEBEMAIL: "smartnic@es.net"
      DEBFULLNAME: "ESnet SmartNIC Developers"
      DEBIAN_FRONTEND: noninteractive
      SN_HW_REPO: ${SN_HW_REPO-unset}
      SN_HW_BRANCH: ${SN_HW_BRANCH-unset}
      SN_HW_APP_NAME: ${SN_HW_APP_NAME?}
      SN_HW_BOARD: ${SN_HW_BOARD?}
      SN_HW_VER: ${SN_HW_VER?}
      SN_FW_REPO: ${SN_FW_REPO-unset}
      SN_FW_BRANCH: ${SN_FW_BRANCH-unset}
      SN_FW_VER: ${SN_FW_VER?}
      OS_CODENAME: ${OS_CODENAME?}
    entrypoint:
      - /bin/bash
      - -c
      - -e
      - -o
      - pipefail
      - -x
      - |
        cp -a /source /build
        cd /build/source
        meson subprojects purge --include-cache --confirm
        SN_HW_API="/sn-hw/artifacts.$${SN_HW_BOARD}.$${SN_HW_APP_NAME}.$${SN_HW_VER}.zip"
        [ -r $${SN_HW_API} ] || ( echo "Error - Can't open $${SN_HW_API}" ; exit 1)
        ln -fs \
          $${SN_HW_API} \
          subprojects/packagefiles/esnet-smartnic-hwapi.zip
        meson subprojects download
        mk-build-deps --install \
          --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
          debian/control
        rm -f debian/changelog
        dch --create \
          --package esnet-smartnic \
          --newversion 1.0.0-$${SN_FW_VER} \
          --distribution $${OS_CODENAME} \
          --urgency medium debian/changelog
        dpkg-buildpackage --build=binary -us -uc
        mkdir -p /output/debs/$${OS_CODENAME}
        mkdir -p /output/debs/$${OS_CODENAME}/meson-logs
        cp obj-x86_64-linux-gnu/meson-logs/* /output/debs/$${OS_CODENAME}/meson-logs
        mv ../*-$${SN_FW_VER}_*.{buildinfo,changes,deb,ddeb} /output/debs/$${OS_CODENAME}
        find /output/debs -type d -print0 | xargs --no-run-if-empty --null chmod a=rwx
        find /output/debs -type f -print0 | xargs --no-run-if-empty --null chmod a=rw
        cat <<_EOF > /output/buildinfo.env
        # FW
        SN_FW_REPO=$${SN_FW_REPO}
        SN_FW_BRANCH=$${SN_FW_BRANCH}
        SN_FW_VER=$${SN_FW_VER}
        OS_CODENAME=$${OS_CODENAME}
        # HW
        SN_HW_REPO=$${SN_HW_REPO}
        SN_HW_BRANCH=$${SN_HW_BRANCH}
        SN_HW_APP_NAME=$${SN_HW_APP_NAME}
        SN_HW_BOARD=$${SN_HW_BOARD}
        SN_HW_VER=$${SN_HW_VER}
        _EOF
        file subprojects/esnet-smartnic-hwapi/firmware/esnet-smartnic.bit
