#==============================================
# Application configuration
#
# NOTE: This file is autogenerated.
#==============================================
# Project paths
SMARTNIC_ROOT  := /home/liam/Planter/src/targets/alveo_u280/hardware/model_test/esnet-smartnic-hw
include /home/liam/Planter/src/targets/alveo_u280/hardware/model_test/esnet-smartnic-hw/paths.mk

# Application-specific parameters
export APP_DIR := /home/liam/Planter/src/targets/alveo_u280/hardware/model_test
APP_NAME       := model_test
APP_TYPE       := P4
APP_ROOT       := /home/liam/Planter/src/targets/alveo_u280/hardware/model_test/.app/src/p4_app
BOARD          := au280
BUILD_NAME     := model_test
ARTIFACTS_DIR  := /home/liam/Planter/src/targets/alveo_u280/hardware/model_test/artifacts
P4_FILE        := /home/liam/Planter/src/targets/alveo_u280/hardware/model_test/p4/esnet-smartnic.p4
P4_OPTS        := CONFIG.PKT_RATE {150} CONFIG.OUTPUT_METADATA_FOR_DROPPED_PKTS {true}

# Standard application parameters
include /home/liam/Planter/src/targets/alveo_u280/hardware/model_test/esnet-smartnic-hw/scripts/app_config_base.mk
